# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UliPGoUkSm-xsBU5V6U-y6516emoUT0L
"""

def startquiz(filename):
  try :
    print("------------------------------------------------------")
    print("               Let's Start The Quiz                   ")
    print("------------------------------------------------------")
    while True:
      score=0
      with open(filename,'r') as file:
        l=file.readlines()
        total=len(l)

        for i in l:
          question,a,b,c,d,ans = i.strip().split(',')
          print("\n"+question)
          print("\n"+a+"\n"+b+"\n"+c+"\n"+d+"\n")
          userinput=input("Choose the Correct Option--> A,B,C,D:  ")
          if(userinput.lower()==ans.lower()):
            print("\n Correct Answer!")
            score+=1
          else:
            print("\n"+f"Sorry! Wrong Answer -->The Correct answer is: {ans}")

        print("---------------------------------------------------------")
        print("                  !Final ScoreCard!                      ")
        print("---------------------------------------------------------")
        print(f" The Final Score is {score} out of {total}")
        print("=========================================================")
        print("                 !Thanks For Playing!                      ")
        print("=========================================================")
        print()
        print()
        print("Do You Want to Restart The game Then Type Y for Yes N for No")
        inp=input('Choose The Option --> Y or N:  ')
        if inp.lower()=='n':
          break

  except FileNotFoundError:
    print("File Doesn't Exist Please Check Once!")

startquiz("quiz.txt")